In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
#this saves the array (within the notebook?)
np.save('myarray',arr)

In [6]:
arr = np.array(10)
arr

array(10)

In [7]:
#load original array (because we saved it)
#have to call the .npy extension because we saved it in a npy file called myarray.npy (will see in the filestructure)
np.load('myarray.npy') 

array([0, 1, 2, 3, 4])

In [8]:
# ^ works

In [9]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [16]:
arr2 = np.arange(10) #.arange() NOT .array()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#save them both in a file
#saveZ is important.  Will zip them together.  Need to provide keys for extracting later
np.savez('ziparray.npz',x=arr1,y=arr2)

In [18]:
archive_array = np.load('ziparray.npz')
archive_array

In [19]:
# ^only shows location it is saved.  Need more info for extraction

In [20]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [21]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr = np.array([[1,2,3],[4,5,6]]) #.array() makes matrices
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [26]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')

In [27]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])