In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
##functions that apply to ever value in an array

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
#creat a random array with a normal distribution (or something like that---it will be clarified later)
A = np.random.randn(10)

A

array([ 0.03159695,  0.01284822, -0.39419638,  0.19481444, -1.04404977,
        0.42070524,  0.54164889,  1.05717786,  1.87846919,  0.27888927])

In [8]:
B = np.random.randn(10)
#add corresponding array values together
B

array([ 1.48956397, -1.72685509,  0.71124384, -1.29417722, -0.01809616,
       -0.07239163,  1.37569755,  1.18787421, -1.10753732,  0.80862863])

In [9]:


np.add(A,B)


array([ 1.52116092, -1.71400686,  0.31704746, -1.09936279, -1.06214593,
        0.34831361,  1.91734645,  2.24505208,  0.77093187,  1.0875179 ])

In [10]:
np.maximum(A,B)


array([ 1.48956397,  0.01284822,  0.71124384,  0.19481444, -0.01809616,
        0.42070524,  1.37569755,  1.18787421,  1.87846919,  0.80862863])

In [11]:
#which of those two values is max
#documentation has all the binary functions

website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True